[package]
name = "expr-changelog-generation"
version = "0.1.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
git2 = "0.19.0"
octocrab = "0.42.0"
tokio = { version = "1.41", features = ["rt-multi-thread", "macros", "time"] }
